```{r}
df <- data.frame(
  type = c("chickpea", "red lentil", "soybean", "black soybean", "edamame"),
  pasta = c("penne", "rotini", rep("spaghetti", 3)),
  price = c(2.99, 2.99, 2.75, 2.75, 2.75)*1.07,
  weight_oz = c(12, 12, 7.05, 7.05, 7.05),
  serv_size = c(3, 3, 2, 2, 2),
  cal = c(380, 320, 190, 180, 180),
  total_fat = c(4, 1.5, 4, 3, 3.5),
  K = c(540, 1080, 1120, 1100, 1260)*0.001,
  total_carb = c(61, 62, 20, 19, 20),
  fiber = c(18, 5, 13, 11, 13),
  protein = c(24, 21, 24, 25, 24)
                   )
library(ggplot2)
library(tidyverse)
```

```{r}
df %>% mutate(price_per_oz = price/weight_oz) %>%
  ggplot(aes(x = reorder(type, price_per_oz), y = price_per_oz)) + geom_bar(stat="identity", fill = "chartreuse4") +
  geom_text(aes(label = paste("$", round(price_per_oz, 2), sep="")), vjust=1.6, col = "white") + 
  scale_x_discrete(labels = paste(df$type, df$pasta, sep="\n")) +
  theme(panel.background = element_blank(),
        panel.grid.major.y = element_line(color = "grey90", size = 0.3),
        axis.ticks = element_blank()) +
  labs(x = "Type", y = "Price per oz", title="Price per oz of Pastas")
```

```{r}
df %>% mutate(cal_oz = cal/serv_size,
              total_fat = total_fat/serv_size,
              K = K/serv_size,
              total_carb = total_carb/serv_size,
              fiber = fiber/serv_size,
              protein = protein/serv_size,
              tmpsum = total_fat+K+total_carb+fiber+protein,
              tmp = cal_oz/tmpsum) %>% 
  gather(nutrient, amt, total_fat, K, total_carb, fiber, protein) %>%
  ggplot(aes(x = reorder(type, cal_oz), y = amt*tmp, fill = nutrient)) + 
  geom_bar(stat="identity", position="stack") +
  geom_text(aes(label=round(amt, 2)), position = position_stack(vjust = 0.5), size=3) +
  stat_summary(fun = sum, aes(label = round(..y.., 2), group = type), geom = "text", vjust= -0.7, size=4.2) +
  ylim(0, 150) +
  labs(title = "Nutritional Makeup per calories/oz", y = "Calories per oz", x = "Type", subtitle="Nutrients in g/oz") +
  theme(panel.background = element_blank(),
        panel.grid.major.y = element_line(color = "grey90", size = 0.3),
        axis.ticks = element_blank())
```
